Support Push Button events
The original drive doesn't support Push Button events from either Rule Machine or from the Device details. Both throw an exception:

groovy.lang.MissingMethodException: No signature of method: user_driver_djdizzyd_Zooz_Zen21_Central_Scene_Switch_383.push() is applicable for argument types: (java.math.BigDecimal) values: [1]

or

groovy.lang.MissingMethodException: No signature of method: user_driver_djdizzyd_Zooz_Zen21_Central_Scene_Switch_383.push() is applicable for argument types: (java.lang.Long) values: [1]

This allows the switch to support virtual button pushes.